<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link https://github.com/pacificnm/pacificnm-config for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license https://github.com/pacificnm/pacificnm-config/blob/master/LICENSE.md
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					<i class="fa fa-cog"></i>
					<?php echo $this->translate('Edit Config'); ?>
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body">
				<?php echo $this->form()->openTag($this->form); ?>
				<?php echo $this->partial('partials/form-errors.phtml', array('errorMsg' => $this->form->getMessages())); ?>
				
				<div id="myTabs">
					<ul class="nav nav-tabs" role="tablist">

						<li role="presentation" class="active"><a href="#company"
							aria-controls="company" role="tab" data-toggle="tab"> <i
								class="fa fa-home"></i> <?php echo $this->translate('Company Settings'); ?>
    						</a></li>
						<li role="presentation"><a href="#config" aria-controls="config"
							role="tab" data-toggle="tab"> <i class="fa fa-gear"></i> <?php echo $this->translate('Application Config'); ?>
    						</a></li>
						<li role="presentation"><a href="#email" aria-controls="email"
							role="tab" data-toggle="tab"> <i class="fa fa-gear"></i> <?php echo $this->translate('E-Mail Settings'); ?>
    						</a></li>
					</ul>

					<div class="tab-content">
						<div role="tabpanel" class="tab-pane" id="config">

							<h3 class="profile-username"><?php echo $this->translate('Application Config'); ?></h3>
							
							<div class="row">
								<div class="col-xs-12 col-sm-8">
            						<?php echo $this->formElementDisplay($this->form->get('configThemeId')); ?>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-12 col-sm-4">
            						<?php echo $this->formElementDisplay($this->form->get('configDateLong')); ?>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configDateShort')); ?>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configLang')); ?>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
            						<?php echo $this->formElementDisplay($this->form->get('configCurrency')); ?>					
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
            						<?php echo $this->formElementDisplay($this->form->get('configCopyYear')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12">
									<?php echo $this->formElementDisplay($this->form->get('configRegister')); ?>
								</div>
							</div>
							
							<div class="row">
								<div class="col-xs-12">
									<?php echo $this->formElementDisplay($this->form->get('configResetPassword')); ?>
								</div>
							</div>
						</div>

						<div role="tabpanel" class="tab-pane active" id="company">
							<h3 class="profile-username"><?php echo $this->translate('Company Settings'); ?></h3>
							
							<div class="row">
								<div class="col-xs-12">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyName')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-8">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyNameShort')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyNameAbv')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-8">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyStreet')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-8">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyStreetCont')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyCity')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyState')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyPostal')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyPhone')); ?>
            					</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-4">
									<?php echo $this->formElementDisplay($this->form->get('configCompanyPhoneAlt')); ?>
            					</div>
							</div>
                          	
                          	<div class="row">
								<div class="col-xs-12 col-sm-4">
                          			<?php echo $this->formElementDisplay($this->form->get('submit')); ?>
                          		</div>
                          	</div>
                      	</div>

						<div role="tabpanel" class="tab-pane" id="email">
							<h3><?php echo $this->translate('E-Mail Settings'); ?></h3>
							
							<div class="row">
								<div class="col-xs-12 col-sm-6">
            						<?php $element = $this->form->get('configSmtpHost'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-2">
            						<?php $element = $this->form->get('configSmtpPort'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-6">
            						<?php $element = $this->form->get('configSmtpSecurity'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-12">
            						<?php $element = $this->form->get('configSmtpDisplay'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>



							<div class="row">
								<div class="col-xs-12 col-sm-12">
            						<?php $element = $this->form->get('configSmtpEmail'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-12 col-sm-12">
            						<?php $element = $this->form->get('configSmtpPassword'); ?>
            						<div
										class="form-group <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
										<label class="control-label"><?php echo $element->getLabel() ?></label>
            							<?php echo $this->formElement($element); ?>
            							<?php if($this->formElementErrors($element)): ?>
            								<span class="text-danger"><?php echo $this->formElementErrors($element) ?> </span>
            							<?php endif; ?>
            						</div>
								</div>
							</div>

						</div>
                      	
        				<?php echo $this->formElement($this->form->get('configId')); ?>
        				<?php echo $this->formElement($this->form->get('configVersion')); ?>
        				<?php echo $this->formElement($this->form->get('configHttpAddress')); ?>
        				
        				<?php echo $this->form()->closeTag(); ?>
        			</div>
				</div>
			</div>
		</div>
	</div>
</div>